import { Injectable } from '@angular/core';
import { Quote } from '../models/quote';
import { QuoteSource } from '../models/quote.source';

@Injectable({
  providedIn: 'root'
})
export class QuoteService {
  private quoteSources: QuoteSource[] = [
    { id: 0, text: "All", title: "" },
    { id: 1, text: "Brown Book (Vietnam)", title: "2025 March 23rd Vietnam Ho Chi Minh" },
    { id: 2, text: "Black Book", title: "Will populate when received back" },
  ];

  private quotes: Quote[] = [
    { text: "Ambition kills loneliness\nWisdom kills anger\nDreams kill fear\nGrowth kills ego\nPease kills jealousy\nConfidence kills doubt", sourceId: 2 },
    { text: "In the end, this world will go under because of the stupidity of people", sourceId: 1 },
    { text: "If you don't know where you're going, any road'll take you there", sourceId: 1 },
    { text: "With every mistake, we must surely be learning", sourceId: 1 },
    { text: "As long as you hate, there will be people to hate", sourceId: 1 },
    { text: "All the world is a birthday cake! So take a piece but not too much", sourceId: 1 },
    { text: "Let the Holy Spirit fight your battles. You are fighting with the wrong weapons. You may be weary, worn, broken and beaten down. The world tells you to hustle harder, push more, retaliate and to take control", sourceId: 1 },
    { text: "Heaven and Hell is right now. You make it Heaven or Hell by your actions", sourceId: 1 },
    { text: "I wanted to be successful, not famous", sourceId: 1 },
    { text: "When you are beyond yourself, then you may find peace of mind is waiting there", sourceId: 1 },
    { text: "I don't know karate, but I know ka-razy", sourceId: 1 },
    { text: "I don't play it safe, I take risks", sourceId: 1 },
    { text: "Zechariah 4:6 \"Not by might, nor by power, but by my Spirit, says the Lord.\" That is a declaration of war, that [we] must be one in the Spirit!", sourceId: 1 },
    { text: "You were never meant to be your own savior!", sourceId: 1 },
    { text: "I'm not a millionate, but I feel like one, because I'm blessed with so much talent", sourceId: 1 },
    { text: "Don't terrorize, organize", sourceId: 1 },
    { text: "You got to use what you got, to get what you want", sourceId: 1 },
    { text: "You can't teach others if you are living the same way", sourceId: 1 },
    { text: "\"You got to live for yourself, yourself and nobody else\" - James Brown", sourceId: 1 },
    { text: "David stood before Goliath. He didn't say 'I come at you with a sword'. He said 'I come at you in the name of the Lord'! This is the power of a spirit filed life", sourceId: 1 },
    { text: "Paul said 'When I am weak I am strong' then the Spirit steps in, it is int he surrender", sourceId: 1 },
    { text: "Music is a universal language that can bring people together regardless of their differences", sourceId: 1 },
    { text: "Soul music is about expressing and connecting with you audience on a spiritual level", sourceId: 1 },
    { text: "I want to rock your gypse soul, just like way back in the days of old", sourceId: 1 },
    { text: "You gotta fight everyday, to keep mediocrity at bay", sourceId: 1 },
    { text: "He saved me because I was lost! He called me because I was chosen! Jesus was rejected, who cares what they think, it is about you + me, we were chosen! Are you desparate? Then God will rise you by the breath of the Spirit! Not by the arm of the flesh", sourceId: 1 },
    { text: "I don't need no Guru | Method | Teacher. Just you and I and nature and the Father in the garden", sourceId: 1 },
    { text: "The wild night is calling", sourceId: 1 },
    { text: "Smell the sea and feel the sky", sourceId: 1 },
    { text: "At the end of the day, we should give thanks and pray, to the One, to the One", sourceId: 1 },
    { text: "Don't be manipulated by opinions! Reach a point where your love for God is louder than their rejections. Others pass you by. He knows, He sees, the Lord stands by you", sourceId: 1 },
    { text: "When you feel insignifigant + others ignore your cries, heave, collect your tears. Stop waiting for the world, the Lord stands by you", sourceId: 1 },
    { text: "Spiritual Hunger + Thirst, but you got to change on the inside first to be satisfied", sourceId: 1 },
    { text: "Love of the simple is all I need. I've no time schism, or lovers of greed", sourceId: 1 },
    { text: "No one gets out of here alive", sourceId: 1 },
    { text: "A friend is someone who gives you total freedom to be yourself", sourceId: 1 },
    { text: "He annointed you because you're willing. Don't move for the praises of men, but for Gods Glory. The mission of Heaven, is greater than the opinions of Earth", sourceId: 1 },
    { text: "Joseph: prison did not delay his destiny. His pain didn't cancel the Promise, it qualified him!", sourceId: 1 },
    { text: "God [is] always crafting something in the shadow. He is building character in the cause", sourceId: 1 },
    { text: "Whoever controls the media, controls the mind", sourceId: 1 },
    { text: "The future is uncertain but the end is always near", sourceId: 1 },
    { text: "Where's your will to be wierd", sourceId: 1 },
    { text: "You feel your strength in the experience of pain", sourceId: 1 },
    { text: "It may have been in pieces, but I gave you the best of me", sourceId: 1 },
    { text: "He is forging power in the pain, and when the time is right He will raise you up! And no one will be able to deny what God had done for you. But fix your eyes on the One who authored your story", sourceId: 1 },
    { text: "Held hostage by the approval of the crowd, they measured your success by reactions of the people who don't even pray", sourceId: 1 },
    { text: "People are strange, when you are a stranger", sourceId: 1 },
    { text: "Some of my worst mistakes in life were haircuts", sourceId: 1 },
    { text: "I am the lizard king, I can do anything", sourceId: 1 },
    { text: "Reality leaves a lot to imagination", sourceId: 1 },
    { text: "Living is easy with eyes closed! Misunderstanding all you see", sourceId: 1 },
    { text: "Everything will be okay in the end. It its not okay, then it is not the end", sourceId: 1 },
    { text: "Being honest may not get you a lot of friends, but it will always get you the right ones", sourceId: 1 },
    { text: "One thing you can't hide is when you are crippled inside", sourceId: 1 },
    { text: "Happiness is just how you feel when you don't feel miserable", sourceId: 1 },
    { text: "Everybody loves you, when your 6 feet in the ground", sourceId: 1 },
    { text: "I will make you fishers of men", sourceId: 1 },
    { text: "All your heart | soul | mind - the greatest - and your welcomers[?]", sourceId: 1 },
    { text: "As long as people have problems, the Blues can never die", sourceId: 1 },
    { text: "Hard times don't necessarily mean being poor", sourceId: 1 },
    { text: "Out of everything I've lost, I miss my mind the most", sourceId: 1 },
    { text: "Mental wounds not healing, who and what to blame. I'm going off the rails on a crazy train", sourceId: 1 },
    { text: "Make it not too late to learn how to love and forget how to hate", sourceId: 1 },
    { text: "Rock and roll is my religion", sourceId: 1 },
    { text: "The road to nowhere leads to me", sourceId: 1 },
    { text: "You can shoose, don't confuse, win or lose, its up to you", sourceId: 1 },
    { text: "Be yourself, the other roles are already filled", sourceId: 1 },
    { text: "A man is half what he is, and half what he would like to be", sourceId: 1 },
    { text: "The secret to being boring is knowing how to tell everything about yourself", sourceId: 1 },
    { text: "Always forgive your enemies, nothing irratates them more", sourceId: 1 },
    { text: "Its a terribly hard job to do nothing", sourceId: 1 },
    { text: "The best way yo make children good, is to make them happy", sourceId: 1 },
    { text: "You cannot change the direction of the wind, but you can always raise the sails to reach your goal", sourceId: 1 },
    { text: "Selfishness is not about living as one wants, but about forcing others to live according to ones principles", sourceId: 1 },
    { text: "I don't want to know what people say behind my back at all. I think highly of myself as it is", sourceId: 1 },
    { text: "Every place you love, is the world to you", sourceId: 1 },
    { text: "A womans strength is that she can't be explained psychologically", sourceId: 1 },
    { text: "Keep love in your heart, life without it is like a sunless garden with dead flowers", sourceId: 1 },
    { text: "People always destroy what they love most", sourceId: 1 },
    { text: "There will never be warmth in a house with an icey heart", sourceId: 1 },
    { text: "A man wants to be a womans first love, and a woman wants a mans last romance", sourceId: 1 },
    { text: "First they ignore you. Then they laugh at you. Then they fight you! Then you win", sourceId: 1 },
    { text: "The best way to find yourself, is to lose yourselve int he service of others", sourceId: 1 },
    { text: "Prayer is not asking, it is a longing of the soul", sourceId: 1 },
    { text: "It is better in prayer to have a heart without words than words without a heart", sourceId: 1 },
    { text: "An eye for an eye only ends up making the whole world blind", sourceId: 1 },
    { text: "When things go wrong, don't go with them", sourceId: 1 },
    { text: "Trust is like the sun, you can shut it out for a time but it aint going anywhere", sourceId: 1 },
    { text: "Life is a moment in space, when the dreams are gone its a lonlier place", sourceId: 1 },
    { text: "Love somebody like you. I was holding on for far too long. Cause nothings all that I ever knew. I am still in love with you, with you, without you", sourceId: 1 },
    { text: "And I stood arrow straight. Unecombered bt the weight of all those hustlers and their schemes. I still believed in my dreams. 35 years, where did they go? Like a rock, standing arrow straight, charging fromt he gate.", sourceId: 1 },
    { text: "I don't need no doctor because I know what ailing me. I've been too long away from my baby/ I'm coming down with a misery. I had the Blues so bad, one time it put my face in a permanent frown! You know I'm feeling so much better, I could cake walk into town", sourceId: 1 },
    { text: "You can get happy in the same pants you got pissed off in!", sourceId: 1 },
    { text: "I've joined a dating site for people his age called Carbon Dating", sourceId: 1 },
    { text: "3 times married I got a DVD on how to improve your fourplay. I had to fast foward through the boring bits at the beginning", sourceId: 1, explicit: true },
    { text: "Last night I had beef stew with dumplings. I shouldn't call her that but shes a big girl", sourceId: 1, explicit: true },
    { text: "Step right back and watch me now! Oh, all the damage is done", sourceId: 1 },
    { text: "1 of my most loved songs throughout my life 'Cant find my Way Home' by Blind Faith", sourceId: 1 },
    { text: "'The world will not be destroyed by those who do evil, but those who watch them without doing anything' - Albert Einstine", sourceId: 1 },
    { text: "No more doggin, fallin over with you. I've got to let you go baby, cause thats wiat I got to do. I gave you all my money, let you play me like a fool. You no prety baby thats just every roll woman", sourceId: 1 },
  ];

  getQuotes(): Quote[] {
    return this.quotes;
  }

  getSources(): QuoteSource[] {
    return this.quoteSources;
  }
}